@startuml
User -> Shop: Click finish order
Shop -> "Payment Provider": Redirect to Payment provider
User -> "Payment Provider": Do payment
...
...
"Payment Provider" -> Shop: Payment successful
Shop -> User: Send order confirmation mail
Shop -> Fulfillment: Send order request
note left: What data is send?
Shop -> Shop: Redirect to Succes/Thank you page
Shop -> User: Show Show Succes/Thank you page
...
...
...
Fulfillment -> User: Send lab test
...
...
User -> Lab: Send lab test
...
...
Lab -> "My Check Your Self": Notifaction that lab test was received
note left: Do we want status updates?
"My Check Your Self" -> User: Notifaction that lab test was received by lab
...
...
...
...
Lab -> "My Check Your Self": Notification that lab results are ready
"My Check Your Self" -> User: Notifaction that lab results are ready and User can pick up results
@enduml
